
stages:
    - build
    - test
    - deploy
  
  # Этап сборки
  build:
    stage: build
    image: node:14 # Используем образ Node.js
    script:
      - echo "Building the Vue.js project..."
      - npm install # Устанавливаем зависимости
      - npm run build # Собираем проект
      - mkdir -p artifacts
      - cp -R dist/* artifacts/ # Копируем собранные файлы в артефакты
    artifacts:
      paths:
        - artifacts/
  
  # Этап деплоя
  deploy:
    stage: deploy
    script:
      - echo "Deploying the application..."
      - # Здесь вы можете добавить команды для деплоя вашего приложения
      - echo "Deployment successful!"
    when: on_success
  