name: Doxygen Documentation

on:
  push:
    tags:
      - 'release*'

jobs:
  doxygen:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Doxygen
        run: |
          choco install doxygen.install

      - name: Run Doxygen
        run: |
          & "C:\Program Files\doxygen\bin\doxygen.exe" "C:\Program Files\doxygen\bin\Doxyfile"
  
