name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          cd vue-project 
          ls -la
          npm install
          npm install wait-on --save-dev

      - name: Build documentation
        run:  |
          cd vue-project
          ls -la
          npm run docs:build

      - name: Check built files
        run: |
          cd vue-project
          ls -la vitepress/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: vitepress/.vitepress/dist