name: Deploy Documentation

on:
  push:
    tags:
      - 'RELEASE**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          cd vue-project
          npm install

      - name: Build documentation
        run: |
          cd vue-project
          npx jsdoc -c jsdoc.json --verbose

      - name: Check dist folder
        run: |
          cd vue-project/docs
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: vue-project/docs
          destination_dir: docs
          publish_branch: gh-pages 