name: Run Selenium Tests

on:
  push:
    branches:
      - main
jobs:
  selenium-tests:
    runs-on: ubuntu-latest  

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          cd vue-project 
          ls -la
          npm install
          npm install wait-on --save-dev

      - name: Run project
        run: |
          echo "start proj"
          cd vue-project
          npm run dev &
          npx wait-on http://localhost:5173
          echo "project is started"

      - name: Run Selenium Tests
        run: | 
          echo "Running tests..."
          cd vue-project
          npx mocha
          echo "Tests completed."
